package  com.ytooo.movie;
dialect "java"

import com.ytooo.model.Movie ;
//import java.util.Arrays;
import java.lang.System;
import java.lang.Double;
import com.ytooo.model.Popularity;
import com.ytooo.model.InCome;
import com.ytooo.model.favorityLanguage;
import com.ytooo.model.YearBnous;

import com.ytooo.model.*;

rule "getScore"
    salience 99

    when
      $p:  Movie()
    then
        System.out.println($p.CalcuWRScore());
        System.out.println("in movie rule");
    end;


rule "pupularityScoreFirst"
    salience 98
    when
      $s:  Movie(getCalPopu()>Popularity.first)
    then

        $s.setCalWRScore($s.getCalWRScore()+Popularity.getFirstBonus());
        System.out.println("已为"+$s.getId()+"热度加分");
    end;

rule "pupularityScoreSecond"
    salience 98
    when
      $s:  Movie(getCalPopu()>Popularity.second&&getCalPopu()<Popularity.first)
    then
        $s.setCalWRScore($s.getCalWRScore()+Popularity.getSecondBonus());
        System.out.println("已为"+$s.getId()+"通过热度加分");
    end;



rule "incomeScoreFirst"
    salience 97
    when
      $s:  Movie(getCalIncome()>InCome.first)
    then
        $s.setCalWRScore($s.getCalWRScore()+InCome.getSecondBonus());
        System.out.println("已为"+$s.getId()+"通过收入加分");
    end;

rule "incomeScoreSecond"
    salience 97
    when
      $s:  Movie(getCalIncome()>InCome.second&&getCalIncome()<InCome.first)
    then
        $s.setCalWRScore($s.getCalWRScore()+InCome.getSecondBonus());
        System.out.println("已为"+$s.getId()+"通过热度加分");
    end;


rule "incomeScoreThird"
    salience 97

    when
      $s:  Movie(getCalIncome()>InCome.third&&getCalIncome()<InCome.second)
    then
        $s.setCalWRScore($s.getCalWRScore()+InCome.getThirdBonus());
        System.out.println("已为"+$s.getId()+"通过热度加分");
    end;








rule "yearScore1"
    salience 95
    when
      $s:  Movie(releaseDate<YearBnous.first)
    then
        $s.setCalWRScore($s.getCalWRScore()+YearBnous.getFirstBonus());
        System.out.println("已为"+$s.getId()+"通过年份加分");
    end;

rule "yearScore2"
    salience 95
    when
      $s:  Movie(releaseDate>YearBnous.first&&releaseDate<YearBnous.second)
    then
        $s.setCalWRScore($s.getCalWRScore()+YearBnous.getSecondBonus());
        System.out.println("已为"+$s.getId()+"通过年份加分");
    end;

rule "yearScore5"
    salience 95
    when
      $s:  Movie(releaseDate>YearBnous.second&&releaseDate<YearBnous.third)
    then
        $s.setCalWRScore($s.getCalWRScore()+YearBnous.getThirdBonus());
        System.out.println("已为"+$s.getId()+"通过年份加分");
    end;








//rule "languageScore"
//    salience 96
//    when
//      $s:  Movie( isFavorite())
//    then
//        $s.setCalWRScore($s.getCalWRScore()+favorityLanguage.langBonus);
//        System.out.println("已为"+$s.getId()+"通过语言加分");
//    end;
query   "getScoreMovie"

    $t: Movie(calWRScore > 5)
    end;













//query   "getScoreMovieAbove0" ()
//    //System.out.println("0");
//    $p: Movie(WRscore>0)
//    end;
//
//query   "getScoreMovieAbove9" ()
//    $p: Movie(WRscore>9)
//    end;


//query   "getScoreMovieByCountry" (String $country)
//    $p: Movie(WRScore>2 && country==$country)
//    end;