package  com.ytooo.movie;
dialect "java"

import com.ytooo.model.Movie ;
//import java.util.Arrays;
import java.lang.System;
//global Double leastToTopMovie;
//global Double allMovieMeanScore ;
//
//global java.util.List  list;

//$movie : Movie(movieId != null)
rule "getScore"
    when
      $p:  Movie()
    then
        System.out.println($p.CalcuWRScore());
        System.out.println("in movie rule");
    end;





//rule "fil"
//    when
//      $p:  Movie()
//    then
//        System.out.print($p.getWRScore());
//        System.out.print("in movie rule");
//
//    end;











query   "getScoreMovie"
    $p: Movie(WRscore>5)
    end;













query   "getScoreMovieAbove0" ()
    //System.out.println("0");
    $p: Movie(WRscore>0)
    end;

query   "getScoreMovieAbove9" ()
    $p: Movie(WRscore>9)
    end;


//query   "getScoreMovieByCountry" (String $country)
//    $p: Movie(WRScore>2 && country==$country)
//    end;